#!/bin/bash
#
#                         License
#
# Copyright (C) 2022  David Valin dvalin@redhat.com
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
#
# This script automates the execution of coremark_pro.  It will determine the
# set of default run parameters based on the system configuration.
#
coremark_pro_version="v1.1.2743"
commit="none"
test_name_run="coremark_pro"
arguments="$@"

exit_out()
{
	if [[ $to_use_pcp -eq 1 ]]; then
		stop_pcp_subset
		stop_pcp
		shutdown_pcp
	fi

	echo $1
	exit $2
}

format_iteration_number()
{
	local iter=$1
	local total=$2

	# No padding needed for less than 10 iterations
	if [ $total -lt 10 ]; then
		echo $iter
		return
	fi

	# Calculate number of digits needed
	local digits=${#total}

	# Format with zero padding
	printf "%0${digits}d" $iter
}

if [ ! -f "/tmp/${test_name_run}.out" ]; then
	command="${0} $@"
	$command &> /tmp/${test_name_run}.out
	rtc=$?
	cat /tmp/${test_name_run}.out
	rm /tmp/${test_name_run}.out
	exit $rtc
fi

curdir=`pwd`
if [[ $0 == "./"* ]]; then
	chars=`echo $0 | awk -v RS='/' 'END{print NR-1}'`
	if [[ $chars == 1 ]]; then
		run_dir=`pwd`
	else
		run_dir=`echo $0 | cut -d'/' -f 1-${chars} | cut -d'.' -f2-`
		run_dir="${curdir}${run_dir}"
	fi
elif [[ $0 != "/"* ]]; then
	dir=`echo $0 | rev | cut -d'/' -f2- | rev`
	run_dir="${curdir}/${dir}"
else
	chars=`echo $0 | awk -v RS='/' 'END{print NR-1}'`
	run_dir=`echo $0 | cut -d'/' -f 1-${chars}`
	if [[ $run_dir != "/"* ]]; then
		run_dir=${curdir}/${run_dir}
	fi
fi
cd $run_dir

setup_done=0
out_file=""
show_usage=0
cpu_add=0
powers_2=0
no_overrides=0

summary_file="coremark_pro.summary"
rm -f $summary_file

# Gather hardware information
$curdir/test_tools/gather_data ${curdir}


pull_data()
{
	pro_file=`mktemp /tmp/pro_reduce_data.XXXXX`
	test_name=${1}
	grep "^${test_name}" coremark_pro_run* | cut -d':' -f2 > ${pro_file}
	multicore=0.0
	singlecore=0.0
	scaling=0.0
	iterations=0
	while IFS= read -r line
	do
		let "iterations=$iterations+1"
		value=`echo $line | awk '{print $2}'`
		multicore=`echo "${multicore}+${value}"| bc -l`
		value=`echo $line | awk '{print $3}'`
		singlecore=`echo "${singlecore}+${value}"| bc -l`
		value=`echo $line | awk '{print $4}'`
		scaling=`echo "${scaling}+${value}"| bc -l`
	done < "${pro_file}"
	rm ${pro_file}
	multicore=`echo "${multicore}/${iterations}" | bc -l`
	singlecore=`echo "${singlecore}/${iterations}" | bc -l`
	scaling=`echo "${scaling}/${iterations}" | bc -l`
	printf "%-47s %10.2f %10.2f %10.2f\n" $test_name $multicore $singlecore $scaling >> $summary_file
}

produce_summary_report()
{
	local iter=$1
	local total=$2
	local padded_iter=$(format_iteration_number $iter $total)

	found=0
	while IFS= read -r line
	do
		if [[ $found -eq 1 ]]; then
			if [[ ${line} == "" ]]; then
				echo $line >> $summary_file
				continue
			fi
			if [[ ${line} == "MARK"* ]]; then
				echo $line >> $summary_file
				continue
			fi
			if [[ ${line} == "Mark"* ]]; then
				echo $line >> $summary_file
				continue
			fi
			if [[ ${line} == "-----"* ]]; then
				echo $line >> $summary_file
				continue
			fi
			if [[ ${line} == "CoreMark"* ]]; then
				found=0
			fi
			test_name=`echo $line | awk '{print $1}'`
			pull_data $test_name
			continue
		fi
		if [[ $line == "------"* ]]; then
			found=1
		fi
		echo $line >> $summary_file
	done < "coremark_pro_run_${padded_iter}"
}

generate_csv_file()
{
	#
	# Create the csv file.
	#

	$TOOLS_BIN/test_header_info --front_matter --results_file results.csv --host $to_configuration --sys_type $to_sys_type --tuned $to_tuned_setting --results_version $coremark_pro_version --test_name $test_name
	echo Test:Multi iterations:Single Iterations:Scaling >> results.csv
	items="^cjpeg-rose7-preset ^core ^linear_alg-mid-100x100-sp ^loops-all-mid-10k-sp ^nnet_test ^parser-125k ^radix2-big-64k ^sha-test ^zip-test"
	for i in $items; do
		multi_iter=0.0
		single_iter=0.0
		scaling=0.0
		samples=0
		for j in `ls -d coremark_pro_run_*`; do
			line=`grep $i $j`
			worker=`echo $line | awk '{print $2}'`
			multi_iter=`echo $multi_iter+$worker | bc`
			worker=`echo $line | awk '{print $3}'`
			single_iter=`echo $single_iter+$worker | bc`
			worker=`echo $line | awk '{print $4}'`
			scaling=`echo $scaling+$worker | bc`
			let "samples=$samples+1"
		done
		multi_iter=`echo "scale = 2;$multi_iter / ${samples}.00" | bc -l`
		single_iter=`echo "scale = 2;$single_iter / ${samples}.00" | bc -l`
		scaling=`echo "scale = 2;$scaling / ${samples}.00" | bc -l` 
		name=`echo $i | sed "s/\^//g"`
		echo $name:$multi_iter:$single_iter:$scaling >> results.csv
	done
}

save_results()
{
	value=`grep CoreMark-PRO  coremark_pro.summary | head -1`
	value_out=`echo $value | cut -d' ' -f2,3 | sed "s/ /:/g"`
	echo "Score:${value_out}"  >>  results.csv
	grep -q ":::" results.csv
	if [ $? -eq 0 ]; then
		echo Failed > test_results_report
	else
		echo Ran > test_results_report
	fi
	${curdir}/test_tools/save_results --curdir $curdir --home_root $to_home_root --other_files "$summary_file,coremark_pro_run*,test_results_report" --results results.csv --test_name coremark_pro --tuned_setting $to_tuned_setting --version $coremark_pro_version --user $to_user
}

#
# Update cjpeg-rose7-preset
#

update_options()
{
# $1 opt directory
# $2 opt file
# $3 value 1 set to
# $4 value 2 set to

	index=0

	if [[ ! -f ${1}/${2}_old ]]; then
		while IFS= read -r line
		do
			if [[ $line == *"override WLD_CMD_FLAGS"* ]]; then
				if [ $index -eq 0 ]; then
					echo "override WLD_CMD_FLAGS=${3}" >> ${2}_new
					let "index=${index}+1"
				else
					echo "override WLD_CMD_FLAGS=${4}" >> ${2}_new
				fi
				continue
			fi
			echo $line >> ${2}_new
		done < "${1}/${2}"
		mv ${1}/${2} ${1}/${2}_old
		mv ${2}_new ${1}/${2}
	fi
}

update_build_options()
{
	pushd workloads > /dev/null

	update_options cjpeg-rose7-preset cjpeg-rose7-preset.opt "-i2000" "-i50000"
	update_options core core.opt "-i1000" "-i1000"
	update_options linear_alg-mid-100x100-sp linear_alg-mid-100x100-sp.opt "-i3000" "-i100000"
	update_options loops-all-mid-10k-sp loops-all-mid-10k-sp.opt "-i1000" "-i2000"
	update_options nnet_test nnet_test.opt "-i1000" "-i3000"
	update_options parser-125k parser-125k.opt "-i1000" "-i1000"
	update_options radix2-big-64k radix2-big-64k.opt "-i10000" "-i200000"
	update_options sha-test sha-test.opt "-i3000" "-i100000"
	update_options zip-test zip-test.opt "-i2000" "-i40000"

	popd >/dev/null
}

run_coremark_pro()
{
	if [ ! -d coremark-pro ]; then
		if [[ $commit == "none" ]]; then
			GIT_TERMINAL_PROMPT=0 git -c advice.detachedHead=false clone --depth 1 --branch ${coremark_pro_version} https://github.com/eembc/coremark-pro
			if [ $? -ne 0 ]; then
				exit_out "Failed to clone https://github.com/eembc/coremark-pro version ${coremark_pro_version}" 1
			fi
		else
			GIT_TERMINAL_PROMPT=0 git -c advice.detachedHead=false clone https://github.com/eembc/coremark-pro
			if [ $? != 0 ]; then
				exit_out "Failed to clone https://github.com/eembc/coremark-pro" 1
			fi
			pushd coremark-pro > /dev/null
			GIT_TERMINAL_PROMPT=0 git checkout ${commit}
			if [ $? -ne 0 ]; then
				exit_out "Failed to checkout ${commit}" 1
			fi
			popd > /dev/null
		fi
	fi
	pushd coremark-pro > /dev/null

	if [ $to_use_pcp -eq 1 ]; then
		source $TOOLS_BIN/pcp/pcp_commands.inc
		setup_pcp
		pcp_cfg=$TOOLS_BIN/pcp/default.cfg
		pcp_dir=/tmp/pcp_coremark-pro_$(date +%Y.%m.%d-%H.%M.%S)
		start_pcp $pcp_dir coremark-pro $pcp_cfg
	fi

	#
	# Iteration of test.
	#
	if [ $no_overrides -eq 0 ]; then
		update_build_options
	fi
	#
	# Silence warnings etc.
	#
	make TARGET=linux64 build >>/dev/null 2>&1
	if [ $? -ne 0 ]; then
		#
		# Make failed, rerun and do not keep quiet about it.
		#
		make TARGET=linux64 build
		exit_out "make of test failed, exiting" 1
	fi
	numb_cpus=`cat /proc/cpuinfo | grep processor | wc -l`
	for iter in $(seq 1 1 $to_times_to_run); do
		
		#If we're using PCP, snap a chalk line at the start of the iteration and log the run number
		if [[ $to_use_pcp -eq 1 ]]; then
        	start_pcp_subset
			result2pcp iteration ${run_number}
		fi

		
		make_flags="TARGET=linux64 XCMD=-c${numb_cpus} certify-all"
		padded_iter=$(format_iteration_number $iter $to_times_to_run)
		make -s $make_flags > coremark_pro_run_${padded_iter}
		if [ $? -ne 0 ]; then
			exit_out "Run failed, make $make_flags" 1
		fi

		# If we're using PCP, snap the chalk line at the end of the iteration
		if [[ $to_use_pcp -eq 1 ]]; then
	       	stop_pcp_subset
		fi
	done

	# If we're using PCP, stop logging
    if [[ $to_use_pcp -eq 1 ]]; then
        echo "Stop PCP"
      	stop_pcp
    fi

	for iter in $(seq 1 1 $to_times_to_run); do
		produce_summary_report $iter $to_times_to_run
	done

	generate_csv_file
	save_results
	

	if [ $to_use_pcp -eq 1 ]; then
		shutdown_pcp
	fi

	${curdir}/test_tools/save_results --curdir $curdir --home_root $to_home_root --other_files "$summary_file,coremark_pro_run*,test_results_report,$pcp_dir" --results results.csv --test_name coremark_pro --tuned_setting $to_tuned_setting --version $coremark_pro_version --user $to_user
	popd > /dev/null
}

usage()
{
	echo "$1 Usage:"
	echo "  --commit <n>: Commit to use.  If not designated, will use tag ${coremark_pro_version}"
	echo "  --no-overrides: If present we will not tune the make files"
	echo "  --test_iterations n: number of times to run the test."
	source ${curdir}/test_tools/general_setup --usage
	exit 0
}

#
# Clone the repo that contains the common code and tools
#

install_tools_git()
{
	give_usage=0
	tools_git=https://github.com/redhat-performance/test_tools-wrappers

	found=0
	for arg in "$@"; do
		if [ $found -eq 1 ]; then
			tools_git=$arg
			found=0
		fi
		if [[ $arg == "--tools_git" ]]; then
			found=1
		fi
	
		#
		# We do the usage check here, as we do not want to be calling
		# the common parsers then checking for usage here.  Doing so will
		# result in the script exiting with out giving the test options.
		#
		if [[ $arg == "--usage" ]]; then
			give_usage=1
		fi
	done

	#
	# Check to see if the test tools directory exists.  If it does, we do not need to
	# clone the repo.
	#
	if [ ! -d "${curdir}/test_tools" ]; then
		GIT_TERMINAL_PROMPT=0 git clone $tools_git ${curdir}/test_tools
		if [ $? -ne 0 ]; then
			exit_out "pulling git $tools_git failed." 1
		fi
	fi
	if [ $give_usage -eq 1 ]; then
		usage $0
	fi
}

install_tools_git "$@"
#
# Variables set by general setup.
#
# TOOLS_BIN: points to the tool directory
# to_home_root: home directory
# to_configuration: configuration information
# to_times_to_run: number of times to run the test
# to_pbench: Run the test via pbench
# to_pbench_copy: Copy the data to the pbench repository, not move_it.
# to_puser: User running pbench
# to_run_label: Label for the run
# to_user: User on the test system running the test
# to_sys_type: for results info, basically aws, azure or local
# to_sysname: name of the system
# to_tuned_setting: tuned setting
#

source ${curdir}/test_tools/general_setup "$@"


# Install needed packages based on the wrapper's JSON file
${TOOLS_BIN}/package_tool --no_packages $to_no_pkg_install --wrapper_config ${run_dir}/coremark_pro-packages.json
if [[ $? -ne 0 ]]; then
	exit_out "package_tool reported failure installing dependencies." 1
fi

ARGUMENT_LIST=(
	"commit"
	"test_iterations"
)

NO_ARGUMENTS=(
	"no-overrides"
	"usage"
)

# read arguments
opts=$(getopt \
	--longoptions "$(printf "%s:," "${ARGUMENT_LIST[@]}")" \
	--longoptions "$(printf "%s," "${NO_ARGUMENTS[@]}")" \
	--name "$(basename "$0")" \
	--options "h" \
	-- "$@"
)

eval set --$opts

while [[ $# -gt 0 ]]; do
	case "$1" in
		--commit)
			coremark_pro_version=$2
			commit=$2
			shift 2
		;;
		--no-overrides)
			no_overrides=1
			shift 1
		;;
		--test_iterations)
			to_times_to_run=$2
			shift 2
		;;
		-h)
			usage $0
		;;
		--)
			break
		;;
		*)
			exit_out "option not found $1" 1
		;;
	esac
done

if [[ -d "coremark-pro" ]]; then
	rm -rf coremark-pro
fi
run_coremark_pro

exit 0
